spring:
  datasource:
    url: jdbc:mysql://myblog9.cryyhmsmsnfr.ap-south-1.rds.amazonaws.com:3306/myblogdb9
    username: admin
    password: admin123$

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 5000



